# Funding options for this project.
# This list is community-maintained; funding is optional.
# Uncomment and complete any line below to show a "Sponsor" button.

# github: [natnew]
# open_collective: # Open Collective username
# ko_fi: # Ko-fi username
# custom: ["https://example.org/donate"]
